services:
  vscode-pietrek:
    build:
      context: .
    ports:
      - "8500:8080"
    volumes:
      - ./projects:/home/coder/projects
      - ssh_keys_volume:/home/coder/.ssh
    restart: always

volumes:
  ssh_keys_volume:
